# 入力となる OpenAPI 仕様ファイルのパス
inputSpec: ./docs/api/openapi.yaml

# 生成されたコードの出力先ディレクトリ
outputDir: ./apps/liff/src/api/generated

# 使用するジェネレータ
generatorName: typescript-axios

# 追加オプション
additionalProperties:
  npmName: "@task-mvp/liff-api-client"
  npmVersion: "0.1.0"
  typescriptThreePlus: true
  supportsES6: true
  withInterfaces: true
  usePromise: true 